version: '3.9'

services:
  db:
    image: mysql:latest
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: varun@12
      MYSQL_DATABASE: mydb
      MYSQL_USER: varun
      MYSQL_PASSWORD: varun
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
